### ISSUE TITLE
help with block in hsw12_asm.pm

### ISSUE THREAD

**Issue by chrstphrchvz** [hotwolf/HSW12#21]
Hi Dirk, could you help me with understanding the condition for this block added in 8d336c078cfa3b27f16a2aa7245d9c26852451d3?

https://github.com/hotwolf/HSW12/blob/8d336c078cfa3b27f16a2aa7245d9c26852451d3/Perl/hsw12_asm.pm#L3489-L3492

I'm guessing `$cpcode` could be a misspelling of `$opcode` or `$cpu`. But `psop_cpu` is a subroutine, so I'm confused what the comparison is between.

I understand that the `#ifcpu` and `#ifncpu` are for including code based on whether a file contains pseudo opcode `CPU` for a specific processor. Though that seems tricky since the precompiler step now depends on pseudo opcodes not normally processed until the actual compile run later on. I'm guessing this block is for detecting the `CPU` opcode early, and assign the operand of the `CPU` pseudo opcode to a global variable.

Thanks

**Comment by hotwolf** [comment]
Hello Christopher,

You are right, this is a typo and it should say "if ($**o**pcode eq $psop_cpu)". This is now one more case, where the precompiler interprets pseudo opcodes early. The other case os "EQU", which is interpreted as "#define" (this was implemented to mimic the behavior of the AS12 assembler). So basically these pseudo opcodes are interpreted by both the pre-compiler and the main compiler. In hindsight, a precompiler directive "#CPU" might have been a better implementation, but I didn't have a need for the "#ifcpu" directives until much later.

I've added the "'ifcpu" directives, because I needed to write some universal code for the S12 and S12X to access the interrupt stack frame. Since the two CPUs have a slightly different stack layout I needed an option to write target dependent code.

Regards,
Dirk

**Comment by chrstphrchvz** [comment]
Hi Dirk, thanks for clarifying. I will keep looking and compare with how `EQU` is implemented; I'm still not sure how `psop_cpu` is being used in the condition. If it's to be used as a subroutine, I'm not sure how its getting its arguments; and with `use warnings` it looks like it's trying to use a scalar `$psop_cpu` rather than the subroutine:
```
Use of uninitialized value $hsw12_asm::psop_cpu in string eq at HSW12/Perl/hsw12_asm.pm line 3499
```
